SRC += src/sat/cadical/analyze.cpp \
src/sat/cadical/arena.cpp \
src/sat/cadical/assume.cpp \
src/sat/cadical/averages.cpp \
src/sat/cadical/backtrack.cpp \
src/sat/cadical/backward.cpp \
src/sat/cadical/bins.cpp \
src/sat/cadical/block.cpp \
src/sat/cadical/ccadical.cpp \
src/sat/cadical/checker.cpp \
src/sat/cadical/clause.cpp \
src/sat/cadical/collect.cpp \
src/sat/cadical/compact.cpp \
src/sat/cadical/condition.cpp \
src/sat/cadical/config.cpp \
src/sat/cadical/congruence.cpp \
src/sat/cadical/constrain.cpp \
src/sat/cadical/contract.cpp \
src/sat/cadical/cover.cpp \
src/sat/cadical/decide.cpp \
src/sat/cadical/decompose.cpp \
src/sat/cadical/deduplicate.cpp \
src/sat/cadical/definition.cpp \
src/sat/cadical/drattracer.cpp \
src/sat/cadical/elim.cpp \
src/sat/cadical/elimfast.cpp \
src/sat/cadical/ema.cpp \
src/sat/cadical/extend.cpp \
src/sat/cadical/external.cpp \
src/sat/cadical/external_propagate.cpp \
src/sat/cadical/factor.cpp \
src/sat/cadical/file.cpp \
src/sat/cadical/flags.cpp \
src/sat/cadical/flip.cpp \
src/sat/cadical/format.cpp \
src/sat/cadical/frattracer.cpp \
src/sat/cadical/gates.cpp \
src/sat/cadical/idruptracer.cpp \
src/sat/cadical/instantiate.cpp \
src/sat/cadical/internal.cpp \
src/sat/cadical/ipasir.cpp \
src/sat/cadical/lidruptracer.cpp \
src/sat/cadical/limit.cpp \
src/sat/cadical/logging.cpp \
src/sat/cadical/lookahead.cpp \
src/sat/cadical/lratchecker.cpp \
src/sat/cadical/lrattracer.cpp \
src/sat/cadical/lucky.cpp \
src/sat/cadical/message.cpp \
src/sat/cadical/minimize.cpp \
src/sat/cadical/occs.cpp \
src/sat/cadical/options.cpp \
src/sat/cadical/parse.cpp \
src/sat/cadical/phases.cpp \
src/sat/cadical/probe.cpp \
src/sat/cadical/profile.cpp \
src/sat/cadical/proof.cpp \
src/sat/cadical/propagate.cpp \
src/sat/cadical/queue.cpp \
src/sat/cadical/random.cpp \
src/sat/cadical/reap.cpp \
src/sat/cadical/reduce.cpp \
src/sat/cadical/rephase.cpp \
src/sat/cadical/report.cpp \
src/sat/cadical/resources.cpp \
src/sat/cadical/restart.cpp \
src/sat/cadical/restore.cpp \
src/sat/cadical/score.cpp \
src/sat/cadical/shrink.cpp \
src/sat/cadical/signal.cpp \
src/sat/cadical/solution.cpp \
src/sat/cadical/solver.cpp \
src/sat/cadical/stable.cpp \
src/sat/cadical/stats.cpp \
src/sat/cadical/subsume.cpp \
src/sat/cadical/sweep.cpp \
src/sat/cadical/terminal.cpp \
src/sat/cadical/ternary.cpp \
src/sat/cadical/tier.cpp \
src/sat/cadical/transred.cpp \
src/sat/cadical/unstable.cpp \
src/sat/cadical/util.cpp \
src/sat/cadical/var.cpp \
src/sat/cadical/veripbtracer.cpp \
src/sat/cadical/version.cpp \
src/sat/cadical/vivify.cpp \
src/sat/cadical/walk.cpp \
src/sat/cadical/watch.cpp \
src/sat/cadical/kitten.c
